package com.hobbiesvault.ui.navigation

object Routes {
    const val HOME     = "home"
    const val GAMES    = "games"
    const val GAMES_ADD    = "games/add"
    const val GAMES_DETAIL = "games/detail"
    const val FILMS    = "films"
    const val FILMS_ADD    = "films/add"
    const val FILMS_DETAIL = "films/detail"
    const val SERIES   = "series"
    const val SERIES_ADD    = "series/add"
    const val SERIES_DETAIL = "series/detail"
    const val MANGA    = "manga"
    const val MANGA_ADD    = "manga/add"
    const val MANGA_DETAIL = "manga/detail"
    const val BOOKS    = "books"
    const val BOOKS_ADD    = "books/add"
    const val BOOKS_DETAIL = "books/detail"
    const val SEARCH   = "search"
    const val SETTINGS = "settings"
    const val SETTINGS_APPEARANCE    = "settings/appearance"
    const val SETTINGS_NOTIFICATIONS = "settings/notifications"
    const val SETTINGS_INTEGRATIONS  = "settings/integrations"
    const val SETTINGS_DATA          = "settings/data"
    const val HISTORY  = "history"
    const val STATS    = "stats"
    const val STATS_DETAILS       = "stats/details"
    const val STATS_FILTERED_LIST = "stats/filteredList"
    const val CALENDAR = "calendar"
    const val ABOUT    = "about"
}
